INSERT into operacion (id, operation, result) values (1, 'SUMAR', 10);
INSERT into operacion (id, operation, result) values (2, 'RESTAR', 5);
INSERT into operacion (id, operation, result) values (3, 'MULTIPLICAR', 50);
INSERT into operacion (id, operation, result) values (4, 'DIVIDIR', 2);
INSERT into operacion (id, operation, result) values (5, 'POTENCIA', 100);
INSERT into operacion (id, operation, result) values (6, 'RAIZ', 10);
insert into numero (id, valor, operacion_id) values (1, 7, 1);
insert into numero (id, valor, operacion_id) values (2, 3, 1);
insert into numero (id, valor, operacion_id) values (3, 15, 2);
insert into numero (id, valor, operacion_id) values (4, 10, 2);
insert into numero (id, valor, operacion_id) values (5, 5, 3);
insert into numero (id, valor, operacion_id) values (6, 10, 3);
insert into numero (id, valor, operacion_id) values (7, 100, 4);
insert into numero (id, valor, operacion_id) values (8, 50, 4);
insert into numero (id, valor, operacion_id) values (9, 10, 5);
insert into numero (id, valor, operacion_id) values (10, 2, 5);
insert into numero (id, valor, operacion_id) values (11, 100, 6);
insert into numero (id, valor, operacion_id) values (12, 2, 6);
alter sequence numero_seq restart with 65;
alter sequence operacion_seq restart with 60;