INSERT INTO OPERATIONS_RECORD (id, operation, numbers, result) VALUES (1, 'SUMA', '8,9,7', 24.0);
INSERT INTO OPERATIONS_RECORD (id, operation, numbers, result) VALUES (2, 'RESTA', '12,5', 7.0);
INSERT INTO OPERATIONS_RECORD (id, operation, numbers, result) VALUES (3, 'MULTIPLICACION', '7,9', 63.0);
ALTER SEQUENCE OPERATIONS_RECORD_SEQUENCE RESTART WITH 4;