INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (1, 'Sumar', '[2.0, 2.0, 2.0]', 6.0);
INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (2, 'Restar', '[2.0, 2.0, 2.0]', -2.0);
INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (3, 'Multiplicacion', '2.0 * 2.0', 4.0);
INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (4, 'Division', '2.0 / 2.0', 1.0);
INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (5, 'Nth Root', '√2 4.0', 2.0);
INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (6, 'Nth Root', '√2 8.0', 2.8284271247461903);
INSERT INTO OPERACIONES (ID, OPERATION_TYPE, OPERANDS, RESULT) VALUES (7, 'Potencia', '4.0^4', 256.0);